sonar.organization=rem7474
sonar.projectKey=Rem7474_TeslaCost
sonar.sources=cmd,internal,web/src,backup
sonar.tests=cmd,internal,web/src
sonar.test.inclusions=**/*_test.go,**/*.test.ts
sonar.exclusions=**/*_test.go,**/*.test.ts,migrations/**,web/dist/**,web/coverage/**
sonar.coverage.exclusions=cmd/**,web/src/views/**,web/src/components/**,web/src/main.ts,web/src/router/**,web/src/locales/**,internal/tolldata/**
sonar.go.coverage.reportPaths=coverage/coverage-go/coverage.out
sonar.javascript.lcov.reportPaths=coverage/coverage-web/lcov.info
sonar.cpd.exclusions=migrations/**
